services:
  mongodb:
    image: mongo:7.0
    container_name: peopleflow_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - peopleflow_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peopleflow_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      DB_NAME: ${MONGO_INITDB_DATABASE}
      DB_HOST: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE?authSource=${MONGO_AUTH_SOURCE}}
      DEBUG: ${DEBUG_DOCKER}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_INITDB_DATABASE}
      MONGO_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      API_PORT: ${API_PORT}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    networks:
      - peopleflow_network

volumes:
  mongodb_data:

networks:
  peopleflow_network:
    driver: bridge
